# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-16 19:31
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hoarding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_type', models.IntegerField(choices=[(1, 'Indoor'), (2, 'OutDoor')], default=2)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('dimension_unit', models.IntegerField(choices=[(1, 'inch'), (2, 'feet')], default=2)),
                ('pixel_pitch', models.IntegerField(choices=[(3, 'P3'), (4, 'P4'), (5, 'P5'), (6, 'P6'), (7, 'P7'), (8, 'P8'), (9, 'P9'), (10, 'P10'), (12, 'P12'), (14, 'P14'), (16, 'P16')], default=2)),
                ('h_res', models.PositiveIntegerField(default=0)),
                ('v_res', models.PositiveIntegerField(default=0)),
                ('rate', models.FloatField(default=0)),
                ('start_time', models.TimeField(default='00:00 AM')),
                ('stop_time', models.TimeField(default='00:00 AM')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(default=datetime.datetime(2017, 7, 16, 19, 31, 11, 6910))),
                ('last_heartbeat', models.DateTimeField(default=datetime.datetime(2017, 7, 16, 19, 31, 11, 6957))),
                ('active_status', models.BooleanField(default=False)),
                ('address', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='common.Address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HoardingResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.FileField(null=True, upload_to=b'')),
                ('hoarding', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hoarder.Hoarding')),
            ],
        ),
    ]
