# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hoarder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoarding',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
