# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-16 20:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoarder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoarding',
            name='last_heartbeat',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 16, 20, 23, 29, 920099)),
        ),
        migrations.AlterField(
            model_name='hoarding',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 16, 20, 23, 29, 920051)),
        ),
        migrations.AlterField(
            model_name='hoarding',
            name='pixel_pitch',
            field=models.IntegerField(choices=[(3, 'P3'), (4, 'P4'), (5, 'P5'), (6, 'P6'), (7, 'P7'), (8, 'P8'), (9, 'P9'), (10, 'P10'), (12, 'P12'), (14, 'P14'), (16, 'P16')], default=0),
        ),
    ]
