# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('hoarder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoarding',
            name='address',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='common.Address'),
        ),
    ]
