# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hoarder', '0002_hoarding_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoarding',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
