# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-24 15:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoarder', '0002_auto_20170716_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoarding',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='hoarding',
            name='diagonal_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hoarding',
            name='min_duration',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='hoarding',
            name='display_type',
            field=models.IntegerField(choices=[(1, 'Indoor'), (2, 'OutDoor'), (3, 'CinemaHall')], default=2),
        ),
        migrations.AlterField(
            model_name='hoarding',
            name='last_heartbeat',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 24, 15, 9, 10, 219578)),
        ),
        migrations.AlterField(
            model_name='hoarding',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 24, 15, 9, 10, 219528)),
        ),
    ]
