# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoarder', '0003_auto_20170402_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoarding',
            name='uuid',
        ),
    ]
