# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-24 21:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoarder', '0003_auto_20170724_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoarding',
            name='last_heartbeat',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 24, 21, 41, 47, 518730)),
        ),
        migrations.AlterField(
            model_name='hoarding',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 24, 21, 41, 47, 518680)),
        ),
        migrations.AlterField(
            model_name='hoarding',
            name='start_time',
            field=models.TimeField(default='08:00 AM'),
        ),
        migrations.AlterField(
            model_name='hoarding',
            name='stop_time',
            field=models.TimeField(default='12:00 PM'),
        ),
    ]
