# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 21:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoarder', '0006_auto_20170820_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoarding',
            name='last_heartbeat',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 20, 21, 59, 17, 154118)),
        ),
        migrations.AlterField(
            model_name='hoarding',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 20, 21, 59, 17, 154067)),
        ),
    ]
