# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 18:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoarder', '0007_auto_20170820_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoarding',
            name='last_heartbeat',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 19, 18, 9, 33, 332074)),
        ),
        migrations.AlterField(
            model_name='hoarding',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 19, 18, 9, 33, 331950)),
        ),
    ]
