# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 21:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoarder', '0008_auto_20171119_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoarding',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hoarding',
            name='last_heartbeat',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 14, 21, 47, 29, 163221)),
        ),
        migrations.AlterField(
            model_name='hoarding',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 14, 21, 47, 29, 163178)),
        ),
    ]
