# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 09:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoarder', '0002_hoarding_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertiser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('resource', models.FileField(upload_to=b'')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignHoardings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertiser.Campaign')),
                ('hoarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoarder.Hoarding')),
            ],
        ),
        migrations.RemoveField(
            model_name='ad',
            name='user',
        ),
        migrations.DeleteModel(
            name='Ad',
        ),
    ]
