# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser', '0003_auto_20170331_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='from_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='to_date',
            field=models.DateField(null=True),
        ),
    ]
